### PR TITLE
moved angular files into separate folder

### PR DESCRIPTION
**Pull request by thehashrocket**
It would be cleaner to keep the angular app in it's own app folder under javascript instead of in the root JS folder. this way, if you add other js files later, they'll be kept apart from your angular app.

### CODE REVIEW

**Comment by jesalg** [comment]
Thanks for the PR although unrelated JS files usually go in the vendor/assets/javascripts folder or often times linked to directly when hosted on a public CDN. Also this angular app represents the entire front-end so if anything we can just add a 'helpers' or 'vendors' folder inside  /app/assets/javascripts/ when needed.

**Comment by thehashrocket** [comment]
I was looking at this app as an example: https://github.com/apotry/stockwatch

Perhaps that helps?

**Comment by jesalg** [comment]
Cool. I've followed the lead of couple other popular RoR + Angular examples like these: https://github.com/sectore/CafeTownsend-Angular-Rails & https://github.com/mkwiatkowski/todo-rails4-angularjs

**Comment by thehashrocket** [comment]
Thank you for this. I'm just getting started with merging Rails and Angular so I'm still trying to figure out the "right" way to do it. Those links are helpful, thank you! :)

**Comment by jesalg** [comment]
You're welcome! :)

**Pull request closed without merging**
